### 1. Test Auth endpoints
POST http://localhost:8000/auth/login/
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

### 2. Test Documents List (non authentifié)
GET http://localhost:8000/api/documents/

### 3. Test Documents List (authentifié)
GET http://localhost:8000/api/documents/
Authorization: Token 73bc8d74b487c775294711893f19c50a9b9131e8

### 6. Test Document Detail
GET http://localhost:8000/api/documents/425/
Authorization: Token 73bc8d74b487c775294711893f19c50a9b9131e8

### 4. Test Admin Interface
GET http://localhost:8000/admin/

### 5. Test API Root
GET http://localhost:8000/api/


### 7. Test Document Create
POST http://localhost:8000/api/documents/
Content-Type: application/json
Authorization: Token {{authToken}}

{
    "title": "Test Document",
    "content": "Test Content",
    "parent": null
}

### Get Document
GET http://localhost:8000/api/documents/129
Authorization: Token {{authToken}}